[MV-341] Add preview screen
jellyfish-dev/react-native-membrane-webrtc pull request #61
Opened 2023-03-22 15:27 UTC by skyman503

This change introduces new preview screen that is displayed to the user before joining a call. It also adds opacity animations to the standard buttons.

2023-03-22 15:58 UTC, graszka22 requested changes

2023-03-22 15:58 UTC, graszka22 commented on example/src/screens/Preview.tsx
> +  const getShortUsername = () => {
extract it to `@utils` or something

2023-03-22 16:46 UTC, graszka22 requested changes

2023-03-22 16:46 UTC, graszka22 commented on example/src/screens/Preview.tsx
> +            <Membrane.VideoPreviewView style={styles.membraneVideoPreview} />
Also the preview should be probably mirrored for the front camera, because people are used to looking at their faces in the mirror.

2023-03-23 08:24 UTC, skyman503 commented on example/src/screens/Preview.tsx
> +  const getShortUsername = () => {
Done.

2023-03-23 08:24 UTC, skyman503 commented on example/src/components/buttons/StandardButton.tsx
> +      activeOpacity={!isEnabled ? 1 : 0.7}
Ack.

2023-03-23 09:14 UTC, skyman503 commented on example/src/screens/Preview.tsx
> +    prevScreen === 'CreateRoom' ? 'New meeting' : 'Join meeting';
Done.

2023-03-23 09:23 UTC, graszka22 approved these changes

2023-03-23 09:28 UTC, merged